workflows:
  cd-android-workflow:
    name: CD Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get App Flutter
        script: |
          fdesetup status
          git clone https://github.com/danjho/app-example.git
      - name: List Directory
        script: |
          ls -lah app-example
      - name: Get Flutter Packages
        script: |
          cd app-example
          flutter packages pub get
      - name: Flutter build apk
        script: |
          cd app-example
          flutter build apk --debug
    artifacts:
      - app-example/build/**/outputs/**/*.apk
      - app-example/build/**/outputs/**/mapping.txt
      - flutter_drive.log
  cd-ios-workflow:
    name: CD iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get App Flutter
        script: |
          git clone https://github.com/danjho/app-example.git
      - name: List Directory
        script: |
          ls -lah app-example
      - name: Get Flutter Packages
        script: |
          cd app-example
          flutter packages pub get
      - name: Flutter build ipa
        script: |
          cd app-example
          flutter build ios --debug --no-codesign
    artifacts:
      - app-example/build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
  cd-workflow:
    name: CD Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.0
      vars:
        NEXUS_URL: "http://localhost:8081/"
    scripts:
      - name: Configurando ambiente
        script: |
          mkdir nexus && cd nexus
          curl -v -OL https://download.sonatype.com/nexus/3/nexus-3.74.0-05-unix.tar.gz
          tar xvzf nexus-3.74.0-05-unix.tar.gz
          ./nexus-3.74.0-05/bin/nexus start
          sleep 120

          echo "Atualizando usuário admin do Nexus"
          export NX_PASSWORD=$(cat /Users/builder/clone/nexus/sonatype-work/nexus3/admin.password)
          curl -ifu admin:"${NX_PASSWORD}" \
            -XPUT -H 'Content-Type: application/json' \
            --data '{"userId": "admin","firstName": "Administrator","lastName": "User","emailAddress": "admin@example.org","source": "default","status": "active","readOnly": false,"roles": ["nx-admin"],"externalRoles": []}' \
            $NEXUS_URL/service/rest/v1/security/users/admin

          echo "Alterando senha do usuário admin do Nexus"
          export OLD_PASSWORD=$(cat /Users/builder/clone/nexus/sonatype-work/nexus3/admin.password)
          export NEW_PASSWORD="admin123"
          curl -ifu admin:"${OLD_PASSWORD}" \
            -XPUT -H 'Content-Type: text/plain' \
            --data "${NEW_PASSWORD}" \
            $NEXUS_URL/service/rest/v1/security/users/admin/change-password

          echo "Criando repositório no Nexus"
          export NEXUS_PASS=$(cat /Users/builder/clone/nexus/sonatype-work/nexus3/admin.password)
          curl -v --header "Content-Type: application/json" \
            --request POST \
            --data '{"name": "internal","online": true,"storage": {"blobStoreName": "default","strictContentTypeValidation": true,"writePolicy": "allow_once"},"cleanup": {"policyNames": ["string"]},"component": {"proprietaryComponents": true},"raw": {"contentDisposition": "ATTACHMENT"}}' \
            $NEXUS_URL/v1/repositories/raw/hosted

      - name: Upload do artefato para o Nexus
        script: |
          export NEXUS_PASS="admin123"
          curl -u admin:$NEXUS_PASS --upload-file artifacts/teste.txt $NEXUS_URL/repository/internal/teste.txt
