workflows:
  cd-android-workflow:
    name: CD Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get App Flutter
        script: |
          git clone https://github.com/danjho/app-example.git
      - name: List Directory
        script: |
          ls -lah app-example
      - name: Get Flutter Packages
        script: |
          cd app-example
          flutter packages pub get
      - name: Flutter build apk
        script: |
          cd app-example
          flutter build apk --debug
    artifacts:
      - app-example/build/**/outputs/**/*.apk
      - app-example/build/**/outputs/**/mapping.txt
      - flutter_drive.log
  cd-ios-workflow:
    name: CD iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get App Flutter
        script: |
          git clone https://github.com/danjho/app-example.git
      - name: List Directory
        script: |
          ls -lah app-example
      - name: Get Flutter Packages
        script: |
          cd app-example
          flutter packages pub get
      - name: Flutter build ipa
        script: |
          cd app-example
          flutter build ios --debug --no-codesign
    artifacts:
      - app-example/build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
  cd-workflow:
    name: CD Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.0
      vars:
        NEXUS_URL: "http://34.134.45.90:8081/"
    scripts:
      - name: Configurando ambiente
        script: |
          echo "Instalando Nexus"
          curl -v -OL https://download.sonatype.com/nexus/3/nexus-3.74.0-05-unix.tar.gz
          mkdir nexus && cd nexus
          tar xvzf nexus-3.74.0-05-unix.tar.gz
          ls -lah
          ls -lah nexus-3.74.0-05

      - name: Download artefato do Nexus
        script: |
          echo $NEXUS_URL
          ls -lah
          # curl -u admin:123 --upload-file ./artifacts/teste.txt $NEXUS_URL/repository/raw/
