workflows:
  cd-workflow:
    name: CD Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.7.12
    scripts:
      - name: Clonando repositório Flutter Hello World
        script: |
          git clone https://github.com/danjho/app-example.git
      - name: Listando diretório
        script: |
          ls -lah
      - name: Listando dentro do app-example
        script: |
          ls -lah app-example
