workflows:
  cd-android-workflow:
    name: CD Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get App Flutter
        script: |
          git clone https://github.com/danjho/app-example.git
      - name: List Directory
        script: |
          ls -lah app-example
      - name: Get Flutter Packages
        script: |
          cd app-example
          flutter packages pub get
      - name: Flutter build apk
        script: |
          cd app-example
          flutter build apk --debug
    artifacts:
      - app-example/build/**/outputs/**/*.apk
      - app-example/build/**/outputs/**/mapping.txt
      - flutter_drive.log
  cd-ios-workflow:
    name: CD iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get App Flutter
        script: |
          git clone https://github.com/danjho/app-example.git
      - name: List Directory
        script: |
          ls -lah app-example
      - name: Get Flutter Packages
        script: |
          cd app-example
          flutter packages pub get
      - name: Flutter build ipa
        script: |
          cd app-example
          flutter build ios --debug --no-codesign
    artifacts:
      - app-example/build/ios/ipa/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
